from typing import Tuple

def create_entity() -> int: ...
def add_transform(entity: int, x: float, y: float) -> None: ...
def add_rigidbody(entity: int, vx: float, vy: float, mass: float) -> None: ...
def get_position(entity: int) -> Tuple[float, float]: ...
def add_sprite(entity: int, texture_id: str, width: int = 0, height: int = 0) -> None: ...
def play_animation(entity: int, tag_name: str) -> None: ...
def pause_animation(entity: int) -> None: ...
def resume_animation(entity: int) -> None: ...
def set_animation_looping(entity: int, looping: bool) -> None: ...
def set_animation_frame(entity: int, frame: int) -> None: ...
