from typing import Tuple

def create_entity() -> int: ...
def add_transform(entity: int, x: float, y: float) -> None: ...
def add_rigidbody(entity: int, vx: float, vy: float, mass: float) -> None: ...
def get_position(entity: int) -> Tuple[float, float]: ...
